LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional
LOCAL_C_INCLUDES := system/core/init
LOCAL_CFLAGS := -Wall -DANDROID_TARGET=\"$(TARGET_BOARD_PLATFORM)\"
LOCAL_SRC_FILES := init_msm8953.cpp
ifneq ($(TARGET_LIBINIT_MSM8953_DEFINES_FILE),)
  LOCAL_SRC_FILES += ../../../../$(TARGET_LIBINIT_MSM8953_DEFINES_FILE)
endif
LOCAL_MODULE := libinit_msm8953

include $(BUILD_STATIC_LIBRARY)